r"""The program's version in the forms the build scripts need, read from pyproject.toml (the single source; __init__.py
repeats it and the tests keep the two equal):

    python scripts\version_info.py              prints the PEP 440 version (0.8.0.dev0)
    python scripts\version_info.py --semver     prints it as SemVer 2 for Velopack (0.8.0-dev.0; scripts\pack.ps1)
    python scripts\version_info.py --write      writes scripts\version_info.txt, the Windows version resource that
                                                PyInstaller embeds into wuxian.exe (scripts\wuxian.spec does this too)
"""
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESOURCE = Path(__file__).resolve().with_name("version_info.txt")
PEP440 = re.compile(r"^(?P<release>\d+(?:\.\d+)*)(?:(?P<pre>a|b|rc)(?P<pre_n>\d+))?(?:\.dev(?P<dev>\d+))?$")
PRE_NAMES = {"a": "alpha", "b": "beta", "rc": "rc"}


def version():
    """the version in pyproject.toml"""
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]


def numbers(v):
    """the four numbers of a Windows file version: 0.8.0.dev0 -> (0, 8, 0, 0)"""
    parts = [int(x) for x in PEP440.match(v).group("release").split(".")]
    return tuple((parts + [0, 0, 0, 0])[:4])


def semver(v):
    """PEP 440 -> SemVer 2, which Velopack wants: 0.8.0.dev0 -> 0.8.0-dev.0, 0.8.0a1 -> 0.8.0-alpha.1, 0.8.0rc1.dev2 ->
    0.8.0-rc.1.dev.2, 0.8.0 -> 0.8.0. The release part must have three numbers (0.8 becomes 0.8.0); post releases and local
    versions have no SemVer form and are refused."""
    m = PEP440.match(v)
    if not m:
        raise ValueError(f"no SemVer form for version {v!r} (release[a|b|rcN][.devN] only)")
    release = [int(x) for x in m.group("release").split(".")]
    if len(release) > 3:
        raise ValueError(f"no SemVer form for version {v!r}: more than three release numbers")
    release += [0] * (3 - len(release))
    pre = []
    if m.group("pre"):
        pre += [PRE_NAMES[m.group("pre")], m.group("pre_n")]
    if m.group("dev") is not None:
        pre += ["dev", m.group("dev")]
    return ".".join(map(str, release)) + ("-" + ".".join(pre) if pre else "")


def resource_text(v):
    """the VSVersionInfo literal PyInstaller reads (its own pyi-grab_version format), for wuxian.exe"""
    nums = numbers(v)
    return f"""# -*- coding: utf-8 -*-
# The Windows version resource of wuxian.exe, generated by scripts/version_info.py from pyproject.toml; do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={nums}, prodvers={nums}, mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('080404B0', [
      StringStruct('CompanyName', 'Wuxian Workshop'),
      StringStruct('FileDescription', '无限工坊 Wuxian Workshop'),
      StringStruct('FileVersion', '{v}'),
      StringStruct('InternalName', 'wuxian'),
      StringStruct('OriginalFilename', 'wuxian.exe'),
      StringStruct('ProductName', '无限工坊 Wuxian Workshop'),
      StringStruct('ProductVersion', '{v}')])]),
    VarFileInfo([VarStruct('Translation', [2052, 1200])])
  ]
)
"""


def write_resource(path=RESOURCE, v=None):
    """scripts/version_info.txt for the current version; returns the path"""
    path = Path(path)
    path.write_text(resource_text(v or version()), encoding="utf-8", newline="\n")
    return path


def main(argv=None):
    args = sys.argv[1:] if argv is None else list(argv)
    v = version()
    if "--write" in args:
        write_resource(RESOURCE, v)
    print(semver(v) if "--semver" in args else v)
    return 0


if __name__ == "__main__":
    sys.exit(main())
